# Generated by Django 2.1.5 on 2019-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_price', models.CharField(max_length=100)),
                ('book_type', models.CharField(max_length=100)),
                ('book_image_url', models.CharField(max_length=500)),
                ('book_rating', models.CharField(max_length=5)),
                ('book_available', models.CharField(max_length=5)),
            ],
        ),
    ]
